CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  default_currency VARCHAR(3) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
); 