PRAGMA defer_foreign_keys = ON;--> statement-breakpoint
PRAGMA foreign_keys = OFF;--> statement-breakpoint
CREATE TABLE `__new_recurrence_rules` (`id` text PRIMARY KEY NOT NULL,`owner_id` text NOT NULL,`kind` text NOT NULL,`description` text NOT NULL,`amount_cents` integer NOT NULL,`subcategory_id` text NOT NULL,`account_id` text,`credit_card_id` text,`payment_method_id` text,`frequency` text DEFAULT 'monthly' NOT NULL,`day_of_month` integer NOT NULL,`start_month` text NOT NULL,`end_month` text,`status` text DEFAULT 'active' NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,FOREIGN KEY (`owner_id`) REFERENCES `users`(`id`),FOREIGN KEY (`subcategory_id`) REFERENCES `subcategories`(`id`),FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`),FOREIGN KEY (`credit_card_id`) REFERENCES `credit_cards`(`id`),FOREIGN KEY (`payment_method_id`) REFERENCES `payment_methods`(`id`),CONSTRAINT "recurrence_rules_positive_amount" CHECK(`amount_cents` > 0),CONSTRAINT "recurrence_rules_day_range" CHECK(`day_of_month` BETWEEN 1 AND 31),CONSTRAINT "recurrence_rules_single_target" CHECK((`account_id` IS NOT NULL) <> (`credit_card_id` IS NOT NULL)),CONSTRAINT "recurrence_rules_card_without_payment_method" CHECK(`credit_card_id` IS NULL OR `payment_method_id` IS NULL));--> statement-breakpoint
INSERT INTO `__new_recurrence_rules` (`id`,`owner_id`,`kind`,`description`,`amount_cents`,`subcategory_id`,`account_id`,`credit_card_id`,`payment_method_id`,`frequency`,`day_of_month`,`start_month`,`end_month`,`status`,`created_at`,`updated_at`) SELECT `id`,(SELECT `id` FROM `users` WHERE `username` = migration_owner_username()),`kind`,`description`,`amount_cents`,`subcategory_id`,`account_id`,`credit_card_id`,`payment_method_id`,`frequency`,`day_of_month`,`start_month`,`end_month`,`status`,`created_at`,`updated_at` FROM `recurrence_rules`;--> statement-breakpoint
DROP TABLE `recurrence_rules`;--> statement-breakpoint
ALTER TABLE `__new_recurrence_rules` RENAME TO `recurrence_rules`;--> statement-breakpoint
CREATE INDEX `recurrence_rules_owner_status_idx` ON `recurrence_rules` (`owner_id`,`status`);--> statement-breakpoint
CREATE INDEX `recurrence_rules_account_idx` ON `recurrence_rules` (`account_id`);--> statement-breakpoint
CREATE INDEX `recurrence_rules_card_idx` ON `recurrence_rules` (`credit_card_id`);--> statement-breakpoint
CREATE INDEX `recurrence_rules_status_idx` ON `recurrence_rules` (`status`);--> statement-breakpoint
CREATE TABLE `__new_planned_expenses` (`id` text PRIMARY KEY NOT NULL,`owner_id` text NOT NULL,`budget_month` text NOT NULL,`subcategory_id` text NOT NULL,`name` text NOT NULL,`amount_cents` integer NOT NULL,`account_id` text,`credit_card_id` text,`recurrence_rule_id` text,`sort_order` integer DEFAULT 0 NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,FOREIGN KEY (`owner_id`) REFERENCES `users`(`id`),FOREIGN KEY (`subcategory_id`) REFERENCES `subcategories`(`id`),FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`),FOREIGN KEY (`credit_card_id`) REFERENCES `credit_cards`(`id`),FOREIGN KEY (`recurrence_rule_id`) REFERENCES `recurrence_rules`(`id`),CONSTRAINT "planned_expenses_positive_amount" CHECK(`amount_cents` > 0),CONSTRAINT "planned_expenses_single_source" CHECK((`account_id` IS NOT NULL) <> (`credit_card_id` IS NOT NULL)));--> statement-breakpoint
INSERT INTO `__new_planned_expenses` (`id`,`owner_id`,`budget_month`,`subcategory_id`,`name`,`amount_cents`,`account_id`,`credit_card_id`,`recurrence_rule_id`,`sort_order`,`created_at`,`updated_at`) SELECT `id`,(SELECT `id` FROM `users` WHERE `username` = migration_owner_username()),`budget_month`,`subcategory_id`,`name`,`amount_cents`,`account_id`,`credit_card_id`,`recurrence_rule_id`,`sort_order`,`created_at`,`updated_at` FROM `planned_expenses`;--> statement-breakpoint
DROP TABLE `planned_expenses`;--> statement-breakpoint
ALTER TABLE `__new_planned_expenses` RENAME TO `planned_expenses`;--> statement-breakpoint
CREATE INDEX `planned_expenses_owner_month_idx` ON `planned_expenses` (`owner_id`,`budget_month`);--> statement-breakpoint
CREATE INDEX `planned_expenses_month_subcategory_idx` ON `planned_expenses` (`budget_month`,`subcategory_id`);--> statement-breakpoint
CREATE INDEX `planned_expenses_account_idx` ON `planned_expenses` (`account_id`);--> statement-breakpoint
CREATE INDEX `planned_expenses_card_idx` ON `planned_expenses` (`credit_card_id`);--> statement-breakpoint
PRAGMA foreign_keys = ON;