PRAGMA defer_foreign_keys = ON;--> statement-breakpoint
PRAGMA foreign_keys = OFF;--> statement-breakpoint
DROP INDEX `credit_card_bill_payments_idempotency_unique`;--> statement-breakpoint
CREATE TABLE `__new_credit_card_bill_payments` (`id` text PRIMARY KEY NOT NULL,`owner_id` text NOT NULL,`idempotency_key` text NOT NULL,`bill_id` text NOT NULL,`account_id` text NOT NULL,`payment_transaction_id` text NOT NULL,`payment_date` text NOT NULL,`principal_cents` integer NOT NULL,`interest_cents` integer DEFAULT 0 NOT NULL,`penalty_cents` integer DEFAULT 0 NOT NULL,`notes` text,`reversed_at` text,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,FOREIGN KEY (`owner_id`) REFERENCES `users`(`id`),FOREIGN KEY (`bill_id`) REFERENCES `credit_card_bills`(`id`),FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`),FOREIGN KEY (`payment_transaction_id`) REFERENCES `transactions`(`id`),CONSTRAINT "credit_card_bill_payments_positive_total" CHECK(`principal_cents` + `interest_cents` + `penalty_cents` > 0),CONSTRAINT "credit_card_bill_payments_nonnegative_principal" CHECK(`principal_cents` >= 0),CONSTRAINT "credit_card_bill_payments_nonnegative_interest" CHECK(`interest_cents` >= 0),CONSTRAINT "credit_card_bill_payments_nonnegative_penalty" CHECK(`penalty_cents` >= 0));--> statement-breakpoint
INSERT INTO `__new_credit_card_bill_payments` (`id`,`owner_id`,`idempotency_key`,`bill_id`,`account_id`,`payment_transaction_id`,`payment_date`,`principal_cents`,`interest_cents`,`penalty_cents`,`notes`,`reversed_at`,`created_at`,`updated_at`) SELECT p.`id`,(SELECT c.`owner_id` FROM `credit_card_bills` b JOIN `credit_cards` c ON c.`id` = b.`credit_card_id` WHERE b.`id` = p.`bill_id`),p.`idempotency_key`,p.`bill_id`,p.`account_id`,p.`payment_transaction_id`,p.`payment_date`,p.`principal_cents`,p.`interest_cents`,p.`penalty_cents`,p.`notes`,p.`reversed_at`,p.`created_at`,p.`updated_at` FROM `credit_card_bill_payments` p;--> statement-breakpoint
DROP TABLE `credit_card_bill_payments`;--> statement-breakpoint
ALTER TABLE `__new_credit_card_bill_payments` RENAME TO `credit_card_bill_payments`;--> statement-breakpoint
CREATE UNIQUE INDEX `credit_card_bill_payments_owner_idempotency_unique` ON `credit_card_bill_payments` (`owner_id`,`idempotency_key`);--> statement-breakpoint
CREATE UNIQUE INDEX `credit_card_bill_payments_transaction_unique` ON `credit_card_bill_payments` (`payment_transaction_id`);--> statement-breakpoint
CREATE INDEX `credit_card_bill_payments_owner_bill_idx` ON `credit_card_bill_payments` (`owner_id`,`bill_id`);--> statement-breakpoint
CREATE INDEX `credit_card_bill_payments_bill_idx` ON `credit_card_bill_payments` (`bill_id`);--> statement-breakpoint
CREATE INDEX `credit_card_bill_payments_account_idx` ON `credit_card_bill_payments` (`account_id`);--> statement-breakpoint
PRAGMA foreign_keys = ON;