import { accounts, categories, createDatabaseConnection, creditCards, subcategories, transactions } from "@finances/database";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import { mkdtempSync, rmSync } from "node:fs"; import { tmpdir } from "node:os"; import { resolve } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest"; import { buildServer } from "./server.js";
const migrationsFolder = resolve(process.cwd(), "../../packages/database/drizzle");
describe("canonical transactions API", () => {
  let dir: string; let app: ReturnType<typeof buildServer>; let connection: ReturnType<typeof createDatabaseConnection>;
  beforeEach(() => { dir = mkdtempSync(resolve(tmpdir(), "transactions-test-")); connection = createDatabaseConnection(resolve(dir, "test.sqlite")); migrate(connection.db, { migrationsFolder }); connection.db.insert(accounts).values({ id: "account", name: "Conta", type: "checking" }).run(); connection.db.insert(categories).values({ id: "category", nature: "expense", name: "Casa" }).run(); connection.db.insert(subcategories).values({ id: "subcategory", categoryId: "category", name: "Mercado" }).run(); connection.db.insert(creditCards).values({ id: "card", name: "Cartão", closingDay: 10, dueDay: 20 }).run(); app = buildServer({ connection, logger: false }); });
  afterEach(async () => { await app.close(); rmSync(dir, { recursive: true, force: true }); });
  it("creates, lists, edits metadata, and definitively deletes a cash expense", async () => { const created = await app.inject({ method: "POST", url: "/transactions", payload: { type: "expense", description: "Mercado", amountCents: 10_000, eventDate: "2026-07-10", accountId: "account", subcategoryId: "subcategory" } }); expect(created.statusCode).toBe(201); const id = created.json().id; expect((await app.inject({ method: "GET", url: "/transactions?budgetMonth=2026-07" })).json()).toHaveLength(1); expect((await app.inject({ method: "PATCH", url: `/transactions/${id}/metadata`, payload: { description: "Mercado corrigido", subcategoryId: "subcategory", notes: "ok" } })).json().amountCents).toBe(10_000); expect((await app.inject({ method: "DELETE", url: `/transactions/${id}` })).statusCode).toBe(204); expect(connection.db.select().from(transactions).all()).toEqual([]); });
  it("creates card installments in each bill month and rejects transfer fields", async () => { const installments = await app.inject({ method: "POST", url: "/transactions", payload: { type: "expense", description: "Compra", amountCents: 10_001, eventDate: "2026-07-15", creditCardId: "card", subcategoryId: "subcategory", installmentCount: 2 } }); expect(installments.statusCode).toBe(201); expect(installments.json().map((item: { budgetMonth: string }) => item.budgetMonth)).toEqual(["2026-08", "2026-09"]); const transfer = await app.inject({ method: "POST", url: "/transactions", payload: { type: "expense", description: "Transferir", amountCents: 100, eventDate: "2026-07-10", accountId: "account", destinationAccountId: "other" } }); expect(transfer.statusCode).toBe(400); });
});
